name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Add licence
        run: 'mkdir -p /opt/android-sdk-linux/licenses && cd /opt/android-sdk-linux/licenses && touch android-sdk-license && echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" >> android-sdk-license && touch android-sdk-preview-license && echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" >> android-sdk-preview-license'
      - name: Run tests
        run: ./gradlew test
